// SPDX-FileCopyrightText: Copyright 2023, 谢尔盖||↓ and the Ordo.pink contributors
// SPDX-License-Identifier: MPL-2.0

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/forgot-password.tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/sign-in.tsx";
import * as $7 from "./routes/sign-out.tsx";
import * as $8 from "./routes/sign-up.tsx";
import * as $$0 from "./islands/component.tsx";
import * as $$1 from "./islands/forms/sign-in-form.tsx";
import * as $$2 from "./islands/forms/sign-up-form.tsx";
import * as $$3 from "./islands/pages/index-hero.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/forgot-password.tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/sign-in.tsx": $6,
    "./routes/sign-out.tsx": $7,
    "./routes/sign-up.tsx": $8,
  },
  islands: {
    "./islands/component.tsx": $$0,
    "./islands/forms/sign-in-form.tsx": $$1,
    "./islands/forms/sign-up-form.tsx": $$2,
    "./islands/pages/index-hero.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
