export type Color = {
	inherit: string
	current: string
	transparent: string
	black: string
	white: string
	slate: string
	gray: string
	zinc: string
	neutral: string
	stone: string
	red: string
	orange: string
	amber: string
	yellow: string
	lime: string
	green: string
	emerald: string
	teal: string
	cyan: string
	sky: string
	blue: string
	indigo: string
	violet: string
	purple: string
	fuchsia: string
	pink: string
	rose: string
}
