// SPDX-FileCopyrightText: Copyright 2023, 谢尔盖||↓ and the Ordo.pink contributors
// SPDX-License-Identifier: MIT

import { Jost } from "next/font/google"
import type { Metadata } from "next"
import "@ordo-pink/css/main.css"
import "../components/index-hero.css"
import { PropsWithChildren } from "react"
import { AppProps } from "next/app"

const jost = Jost({ preload: true, subsets: ["latin"], fallback: ["system-ui"] })

export const metadata: Metadata = {
	title: "Ordo.pink",
	description: "Generated by create next app",
}

export default function App({ Component, pageProps }: AppProps) {
	return (
		<div className={jost.className}>
			<Component {...pageProps} />
		</div>
	)
}
