export enum Color {
	GREEN = "green",
	PINK = "pink",
	YELLOW = "yellow",
	BLUE = "blue",
	GRAY = "gray",
	RED = "red",
	INDIGO = "indigo",
	PURPLE = "purple",
	ORANGE = "orange",
	AMBER = "amber",
	LIME = "lime",
	EMERALD = "emerald",
	TEAL = "teal",
	CYAN = "cyan",
	SKY = "sky",
	VIOLET = "violet",
	FUCHSIA = "fuchsia",
	ROSE = "rose",
}
