import type { Core } from "../sdk-core.types"
import { is_uuid } from "../validations.impl"

/** Implements {@link Identifiable.Interface}. */
export const identifiable: Core.Mixin<Identifiable.Interface> = {
	instance: ({ id }) => ({ get_id: () => id, has_id: x => id === x }),
	static: { create_id: () => crypto.randomUUID() },
	validations: { is_id: is_uuid },
}

// --- Types ---

export module Identifiable {
	/** UUID generated by `crypto.randomUUID()`. */
	export type ID = Core.UUIDv4

	export type DTO = [id: ID]

	export type Interface = {
		Instance: {
			/** Get {@link ID} of the entity. */
			get_id: () => ID
			/** Check whether entity has provided {@link ID}. */
			has_id: (id: ID) => boolean
		}
		Plain: { id: ID }
		Static: {
			/** Create a new {@link ID} that is (hopefully) unique. */
			create_id: () => ID
		}
		Validations: {
			/** {@link ID} guard. */
			is_id: (x: any) => x is ID
		}
	}
}
