/*
 * SPDX-FileCopyrightText: Copyright 2025, 谢尔盖 ||↓ and the Ordo.pink contributors
 * SPDX-License-Identifier: Unlicense
 */

import type { Core } from "../core/core.types"

export namespace CoreMixins {
	export namespace Authored {
		/** Author {@link CoreMixins.Identifiable.ID id} used in `created_by` and `updated_by` fields. */
		export type AuthorID = CoreMixins.Identifiable.ID

		export type DTO<$TrackUpdates extends Core.TrackUpdates> = $TrackUpdates extends "with_updates"
			? [created_by: CoreMixins.Authored.AuthorID, updated_by: CoreMixins.Authored.AuthorID]
			: [created_by: CoreMixins.Authored.AuthorID]

		/**
		 * Adds support for **created_by** (and, optionally, **updated_by**) field, represented by {@link AuthorID}.
		 *
		 * To only get type definition for **created_by**, use `Authored.Interface<"without_updates">`.
		 * To get both **created_by** and **updated_by**, use `Authored.Interface<"with_updates">`.
		 */
		export type Interface<$TrackUpdates extends Core.TrackUpdates> = {
			Instance: $TrackUpdates extends "with_updates" ? InstanceWithUpdates : InstanceWithoutUpdates
			Plain: $TrackUpdates extends "with_updates" ? PlainWithUpdates : PlainWithoutUpdates
			Static: {}
			Validations: CoreMixins.Identifiable.Interface["Validations"]
		}

		// --- Internal ---

		type PlainWithoutUpdates = { created_by: CoreMixins.Authored.AuthorID }
		type PlainWithUpdates = PlainWithoutUpdates & { updated_by: CoreMixins.Authored.AuthorID }

		type InstanceWithoutUpdates = {
			/** Get the {@link CoreMixins.Authored.AuthorID author id} the entity was created by. */
			get_created_by: () => CoreMixins.Authored.AuthorID

			/** Check if entity was created by given {@link CoreMixins.Authored.AuthorID author id}. */
			is_created_by: (id: CoreMixins.Authored.AuthorID) => boolean
		}
		type InstanceWithUpdates = InstanceWithoutUpdates & {
			/** Get the {@link CoreMixins.Authored.AuthorID author id} the entity was last modified by. */
			get_updated_by: () => CoreMixins.Authored.AuthorID

			/** Check if entity was last modified by given {@link CoreMixins.Authored.AuthorID author id}. */
			is_updated_by: (id: CoreMixins.Authored.AuthorID) => boolean
		}
	}

	export namespace Creatable {
		/** Adds support for creating instances of other interfaces with predefined args. */
		export type Interface<$Args extends any[], $Interface extends Core.BaseInterface> = {
			Instance: {}
			Plain: {}
			Static: {
				/** Create a new instance. */
				new: (...args: $Args) => Core.Prettify<$Interface["Instance"]>
			}
			Validations: {}
		}
	}

	export namespace Extendable {
		export type Extensions = Record<string, unknown>

		export type DTO = [extensions: CoreMixins.Extendable.Extensions]

		export type Interface = {
			Instance: {
				get_extension: <$ExpectedValue>(key: string) => $ExpectedValue | null
				has_extension: (key: string) => boolean
			}
			Plain: { extensions: CoreMixins.Extendable.Extensions }
			Static: { get_default_extensions: () => CoreMixins.Extendable.Extensions }
			Validations: { is_extensions: (x: any) => x is CoreMixins.Extendable.Extensions }
		}
	}

	export namespace Identifiable {
		/** UUID generated by `crypto.randomUUID()`. */
		export type ID = Core.UUIDv4

		export type DTO = [id: CoreMixins.Identifiable.ID]

		export type Interface = {
			Instance: {
				/** Get {@link CoreMixins.Identifiable.ID id} of the entity. */
				get_id: () => CoreMixins.Identifiable.ID
				/** Check whether entity has provided {@link CoreMixins.Identifiable.ID id}. */
				has_id: (id: CoreMixins.Identifiable.ID) => boolean
			}
			Plain: { id: CoreMixins.Identifiable.ID }
			Static: {
				/** Create a new {@link CoreMixins.Identifiable.ID} that is (hopefully) unique. */
				create_id: () => CoreMixins.Identifiable.ID
			}
			Validations: {
				/** {@link CoreMixins.Identifiable.ID Id} guard. */
				is_id: (x: any) => x is CoreMixins.Identifiable.ID
			}
		}
	}

	export namespace Named {
		export type Name = string & {}

		export type DTO = [name: CoreMixins.Named.Name]

		export type Interface = {
			Instance: { get_name: () => CoreMixins.Named.Name }
			Plain: { name: CoreMixins.Named.Name }
			Static: { get_default_name: () => CoreMixins.Named.Name }
			Validations: { is_name: (x: any) => x is CoreMixins.Named.Name }
		}
	}

	export namespace Timestampable {
		export type Timestamp = number & {}

		export type DTO<$TrackUpdates extends Core.TrackUpdates> = $TrackUpdates extends "with_updates"
			? [created_at: CoreMixins.Timestampable.Timestamp, updated_at: CoreMixins.Timestampable.Timestamp]
			: [created_at: CoreMixins.Timestampable.Timestamp]

		export type Interface<$TrackUpdates extends Core.TrackUpdates> = {
			Instance: $TrackUpdates extends "with_updates" ? InstanceWithUpdates : InstanceWithoutUpdates
			Plain: $TrackUpdates extends "with_updates" ? PlainWithUpdates : PlainWithoutUpdates
			Static: { create_timestamp: () => CoreMixins.Timestampable.Timestamp }
			Validations: { is_timestamp: (x: any) => x is CoreMixins.Timestampable.Timestamp }
		}

		// --- Internal ---

		type InstanceWithoutUpdates = {
			get_created_at: () => Date
			get_raw_created_at: () => CoreMixins.Timestampable.Timestamp
			is_created_after: (date: Date, exclude_exact_match?: boolean) => boolean
			is_created_before: (date: Date, exclude_exact_match?: boolean) => boolean
		}

		type InstanceWithUpdates = InstanceWithoutUpdates & {
			get_raw_updated_at: () => CoreMixins.Timestampable.Timestamp
			get_updated_at: () => Date
			is_updated_after: (date: Date, exclude_exact_match?: boolean) => boolean
			is_updated_before: (date: Date, exclude_exact_match?: boolean) => boolean
		}

		type PlainWithoutUpdates = { created_at: CoreMixins.Timestampable.Timestamp }
		type PlainWithUpdates = PlainWithoutUpdates & { updated_at: CoreMixins.Timestampable.Timestamp }
	}

	export namespace Serializable {
		export type Interface<$DTO extends any[], $Interface extends Core.BaseInterface> = {
			Instance: { to_dto: () => $DTO }
			Plain: $Interface["Plain"]
			Static: { from_dto: (...dto: $DTO) => Core.Prettify<$Interface["Instance"] & { to_dto: () => $DTO }> }
			Validations: { is_dto: (x: any) => x is $DTO }
		}
	}
}
