name: publish

on:
  release:
    types: [released]

  workflow_dispatch:

jobs:

  npm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@ordo-pink'

      - name: Install dependencies
        run: npm ci

      - name: Put version to package.json
        run: |
          sed -i s/"\"version\":.*/\"version\": \"$GITHUB_REF_NAME\","/ package.json

      - name: Build package
        run: npm run build:prod

      - name: Publish to NPM
        run: npm publish ./dist       
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  ghp:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ordo-pink'

      - name: Install dependencies
        run: npm ci
    
      - name: Put version to package.json
        run: |
          sed -i s/"\"version\":.*/\"version\": \"$GITHUB_REF_NAME\","/ package.json
   
      - name: Build package
        run: npm run build:prod
  
      - name: Publish to NPM
        run: npm publish ./dist       
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHP_TOKEN }}
